services:
  openchallenges-apex:
    image: ghcr.io/sage-bionetworks/openchallenges-apex:${OPENCHALLENGES_VERSION:-local}
    container_name: openchallenges-apex
    restart: always
    env_file:
      - ../../../apps/openchallenges/apex/.env
    volumes:
      - ../../../apps/openchallenges/apex/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - openchallenges
    ports:
      - '8000:8000'
    depends_on:
      openchallenges-api-gateway:
        condition: service_started
      openchallenges-app:
        condition: service_started
      openchallenges-mcp-server:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 200M
