services:
  openchallenges-prometheus:
    image: ghcr.io/sage-bionetworks/openchallenges-prometheus:${OPENCHALLENGES_VERSION:-local}
    container_name: openchallenges-prometheus
    restart: always
    env_file:
      - ../../../apps/openchallenges/prometheus/.env
    networks:
      - openchallenges
    ports:
      - '9090:9090'
    volumes:
      - ../../../apps/openchallenges/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - openchallenges-prometheus-data:/prometheus
    depends_on:
      openchallenges-mysqld-exporter:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 200M
