services:
  openchallenges-vault:
    image: ghcr.io/sage-bionetworks/openchallenges-vault:${OPENCHALLENGES_VERSION:-local}
    container_name: openchallenges-vault
    restart: always
    env_file:
      - ../../../apps/openchallenges/vault/.env
    networks:
      - openchallenges
    ports:
      - '8200:8200'
    cap_add:
      - IPC_LOCK
    deploy:
      resources:
        limits:
          memory: 500M
