site_name: Sage Monorepo
site_description: A development environment for building robust apps faster.
repo_url: https://github.com/Sage-Bionetworks/sage-monorepo
repo_name: sage-monorepo
nav:
  - Home:
      - Sage Monorepo: index.md
      - What's new: news.md
      - Contributing:
          - Overview: contributions/overview.md
          - Reporting a bug: contributions/bug-report.md
          - Adding a feature: contributions/guidelines.md
  - Getting Started:
      - What is Angular Universal?: getting-started/what-is-angular.md
      - What is a devcontainer?: getting-started/what-is-devcontainer.md
      - What is Nx?: getting-started/what-is-nx.md
      - Setup:
          - Develop Locally: getting-started/local-dev.md
          - Develop On a Remote Host: getting-started/remote-dev.md
  - Tutorials:
      - Angular:
          - Create an Angular app: tutorials/angular/add-app.md
          - Add an Angular API client: tutorials/angular/add-api-client.md
          - Add an Angular component: tutorials/angular/add-component.md
          - Add an Angular library: tutorials/angular/add-library.md
      - Docker:
          - Create a Docker-based project: tutorials/docker/new-project.md
      - Java:
          - Add a Java library: tutorials/java/add-library.md
          - Add a Java REST API: tutorials/java/add-rest-api.md
      - Python:
          - Add a Python REST API: tutorials/python/add-rest-api.md
      - R:
          - Add an R project: tutorials/r/new-project.md
  - Developers Guide:
      - Developing on a remote host: developers-guide/developing-on-a-remote-host.md
      - Creating a commit with multiple authors: developers-guide/creating-a-commit-with-multiple-authors.md
      - Common Issues: developers-guide/faq.md
  - Reference:
      - Service Catalog: reference/services.md
      - Agora:
          - API: reference/agora.md
      - OpenChallenges:
          - Microservices: reference/oc-microservices.md
          - Schemas: reference/oc-schemas.md
      - API:
          - Synapse: reference/api/synapse.md
          - Openchallenges: reference/api/openchallenges.md
          - Model-ad: reference/api/model-ad.md
          - Bixarena: reference/api/bixarena.md
          - Amp-als: reference/api/amp-als.md
          - Agora: reference/api/agora.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: images/sage.png
  icon:
    admonition:
      note: octicons/tag-16
      info: octicons/info-16
  features:
    - content.code.copy
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
plugins:
  - autorefs
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
