site_name: Sage Monorepo
site_description: A development environment for building robust apps faster.
repo_url: https://github.com/Sage-Bionetworks/sage-monorepo
repo_name: sage-monorepo
nav:
  - Home: index.md
  - Updates:
      - Overview: updates/index.md
      - September 2025: updates/september-2025.md
      - June 2022: updates/june-2022.md
      - May 2022: updates/may-2022.md
      - April 2022: updates/april-2022.md
      - March 2022: updates/march-2022.md
      - February 2022: updates/february-2022.md
  - Blog: blog/index.md
  - Products:
      - Service Catalog: products/services.md
      - Agora: products/agora.md
      - AMP-ALS: api/amp-als.md
      - BixArena: api/bixarena.md
      - Model-AD: api/model-ad.md
      - OpenChallenges: products/openchallenges.md
      - Synapse: api/synapse.md
  - Develop:
      - Quick Start: develop/quick-start.md
      - Remote Development: develop/remote-dev.md
      - Architecture:
          - Nx Workspace: develop/architecture/what-is-nx.md
          - Dev Containers: develop/architecture/what-is-devcontainer.md
          - Terraform Infrastructure: develop/architecture/terraform-infrastructure.md
      - Tutorials:
          - Angular:
              - Create App: develop/tutorials/angular/add-app.md
              - Add API Client: develop/tutorials/angular/add-api-client.md
              - Add Component: develop/tutorials/angular/add-component.md
              - Add Library: develop/tutorials/angular/add-library.md
          - Java:
              - Add Library: develop/tutorials/java/add-library.md
              - Add REST API: develop/tutorials/java/add-rest-api.md
          - Python:
              - Add REST API: develop/tutorials/python/add-rest-api.md
          - Docker:
              - New Project: develop/tutorials/docker/new-project.md
          - R:
              - New Project: develop/tutorials/r/new-project.md
          - Terraform:
              - Create Backend: develop/tutorials/terraform/create-backend.md
              - Create Reusable Module: develop/tutorials/terraform/create-reusable-module.md
      - Maintenance:
          - Overview: develop/maintenance/index.md
          - Java: develop/maintenance/java.md
          - Node / TypeScript: develop/maintenance/node.md
          - Python: develop/maintenance/python.md
          - R: develop/maintenance/r.md
          - Docker Base Images: develop/maintenance/docker-images.md
          - Dev Container: develop/maintenance/dev-container.md
          - Security & Compliance: develop/maintenance/security.md
          - Troubleshooting & FAQ: develop/maintenance/troubleshooting.md
      - Advanced:
          - Remote Development: develop/advanced/developing-on-a-remote-host.md
          - Multi-author Commits: develop/advanced/creating-a-commit-with-multiple-authors.md
  - API:
      - Overview: api/overview.md
      - Agora: api/agora.md
      - AMP-ALS: api/amp-als.md
      - BixArena: api/bixarena.md
      - Model-AD: api/model-ad.md
      - OpenChallenges: api/openchallenges.md
      - Synapse: api/synapse.md
  - Resources:
      - FAQ: resources/faq.md
      - Bug Reports: resources/bug-report.md
      - Feature Requests: resources/feature-requests.md
      - Contributing: contributions/overview.md
      - OpenChallenges Schemas: resources/oc-schemas.md
  - Technical Documentation:
      - Overview: technical-documentation-overview.md
      - Submission Workflow: submission-workflow.md
      - RFCs: rfcs/README.md
      - Architecture: architecture/README.md
      - ADRs: adr/README.md
theme:
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: images/sage.png
  icon:
    admonition:
      note: octicons/tag-16
      info: octicons/info-16
  features:
    - content.code.copy
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
plugins:
  - autorefs
  - search
markdown_extensions:
  - admonition
  - mdx_truly_sane_lists
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - toc:
      permalink: true
