version: "3.8"

services:
  challenge-keycloak:
    image: sagebionetworks/challenge-keycloak:latest
    container_name: challenge-keycloak
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/h2:/opt/keycloak/data/h2
    # networks:
    #   - challenge
    network_mode: "host"
    ports:
      - "8080:8080"
    command: start-dev

# networks:
#   challenge:
#     name: challenge