version: "3.8"

services:
  api:
    env_file: ${DOT_ENV_FILE}
    # Ensure specific environment variables are ALWAYS available.
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PYTHONUNBUFFERED=1
    build:
      context: ./
      dockerfile: Dockerfile-dev
      args:
        pythonImageVersion: ${PYTHON_IMAGE_VERSION}
    container_name: iatlas-api-dev
    ports:
      - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    volumes:
      - .:/project:delegated
      - ~/.gitconfig:/root/.gitconfig:delegated
      - ~/.ssh:/root/.ssh:delegated
      - iatlas-api-dev-root-vol:/root:delegated
    logging:
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  iatlas-api-dev-root-vol:
