# Staging profile configuration
spring:
  jpa:
    show-sql: false
  datasource:
    url: jdbc:postgresql://openchallenges-postgres-stage:8091/openchallenges?currentSchema=auth
  flyway:
    enabled: false

app:
  api-key:
    prefix: oc_stage_
    length: 40

logging:
  level:
    org.sagebionetworks.openchallenges: INFO
