# Development profile configuration
spring:
  datasource:
    url: jdbc:postgresql://openchallenges-postgres:8091/openchallenges?currentSchema=organization
    username: organization_service
    password: changeme
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
  flyway:
    clean-disabled: false # Allow clean in dev environment
    locations:
      - classpath:db/migration/common # Schema migrations
      - classpath:db/migration/dev # Mock data migrations

logging:
  level:
    org.sagebionetworks.openchallenges: DEBUG
