# Staging profile configuration
spring:
  datasource:
    url: jdbc:postgresql://openchallenges-postgres-stage:8091/openchallenges?currentSchema=organization
    username: organization_service
    password: changeme
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
  flyway:
    enabled: true
    clean-disabled: true # Never clean stage database
    locations:
      - classpath:db/migration/common # Schema migrations only

logging:
  level:
    org.sagebionetworks.openchallenges: INFO
