# Development profile configuration
spring:
  datasource:
    url: jdbc:postgresql://openchallenges-postgres:8091/openchallenges?currentSchema=organization
    username: organization_service
    password: changeme
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false

logging:
  level:
    org.sagebionetworks.openchallenges: DEBUG
