server:
  port: 3334
  forward-headers-strategy: native

spring:
  application:
    name: model-ad-api-next
  data:
    mongodb:
      host: model-ad-mongo
      port: 27017
      database: model-ad
      username: root
      password: changeme
      authentication-database: admin
  jackson:
    date-format: org.sagebionetworks.model.ad.api.next.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
