server:
  port: ${SERVER_PORT:3334}

spring:
  application:
    name: model-ad-api-next
  data:
    mongodb:
      host: ${MODEL_AD_MONGO_HOST:model-ad-mongo}
      port: ${MODEL_AD_MONGO_PORT:27017}
      database: ${MODEL_AD_MONGO_DATABASE:model-ad}
      username: ${MODEL_AD_MONGO_USERNAME:root}
      password: ${MODEL_AD_MONGO_PASSWORD:changeme}
      authentication-database: ${MODEL_AD_MONGO_AUTH_DB:admin}
  jackson:
    date-format: org.sagebionetworks.model.ad.api.next.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
