spring:
  application:
    name: challenge-core-service
  datasource:
    url: ${db.url}
    username: maria
    password: changeme
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: ${service.registry.url}
  instance:
    preferIpAddress: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info

info:
  app:
    name: ${spring.application.name}