openchallenges-mcp-server:
  welcome-message: 'Welcome to the OpenChallenges MCP Server - dev mode'
  api-base-url: http://openchallenges-api-gateway:8082/api/v1

server:
  port: 8887
spring:
  application:
    name: openchallenges-mcp-server
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: openchallenges-mcp-server
        version: 1.0.0
        protocol: STREAMABLE
