spring:
  application:
    name: challenge-user-service
  datasource:
    # url: jdbc:mysql://challenge-mariadb:3306/challenge
    url: ${db.url}
    # url: jdbc:h2:mem:challenge
    username: challenge_user_service
    password: changeme
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    service-url:
      # defaultZone: ${service.registry.url}
      defaultZone: http://challenge-service-registry:8081/eureka
  instance:
    preferIpAddress: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info

info:
  application:
    name: ${spring.application.name}

keycloak:
  realm: test
  resource: challenge-user-service
  credentials:
    secret: GFRau7cQTxhx19CUmSdrqrqrZ1pshjjB
  # auth-server-url: ${keycloak.url}
  auth-server-url: http://challenge-keycloak:8080
  ssl-required: external
  use-resource-role-mappings: true
  bearer-only: true

app:
  config:
    keycloak:
      # server-url: ${keycloak.url}
      server-url: http://challenge-keycloak:8080
      realm: test
      # TODO: Which client ID property is used?
      client-id: challenge-api-client
      clientId: challenge-api-client
      client-secret: mg2DrRcxHx19PIITibdOnbNEbJUKjGKb

springdoc:
  # version: '@springdoc.version@'
  swagger-ui:
    path: /api/v1/api-docs/ui
  api-docs:
    path: /api/v1/api-docs/openapi.json
    #path: /api/v1/openapi.json
  packagesToScan: org.sagebionetworks.challenge.controller
  pathsToMatch: /**

example:
  firstProperty: "main"
