spring:
  application:
    name: challenge-user-service
  datasource:
    # url: jdbc:mysql://challenge-mariadb:3306/challenge
    url: ${db.url}
    # url: jdbc:h2:mem:challenge
    username: challenge_user_service
    password: changeme
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    date-format: org.sagebionetworks.challenge.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${service.registry.url}
  instance:
    preferIpAddress: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health

info:
  application:
    name: ${spring.application.name}

keycloak:
  realm: test
  resource: challenge-user-service
  credentials:
    secret: GFRau7cQTxhx19CUmSdrqrqrZ1pshjjB
  auth-server-url: ${keycloak.url}
  ssl-required: external
  use-resource-role-mappings: true
  bearer-only: true

app:
  config:
    keycloak:
      server-url: ${keycloak.url}
      realm: test
      # TODO: Which client ID property is used?
      client-id: challenge-api-client
      clientId: challenge-api-client
      client-secret: mg2DrRcxHx19PIITibdOnbNEbJUKjGKb

# springdoc:
#   version: openapi_3_1
#   swagger-ui:
#     path: /api/v1/api-docs/ui
#     # url: /api/v1/api-docs/openapi.json
#   api-docs:
#     enabled: true
#     path: /api/v1/api-docs/openapi.json
#   packagesToScan: org.sagebionetworks.challenge.controller
#   pathsToMatch: /**
