# Development profile configuration
spring:
  jpa:
    show-sql: false
  flyway:
    clean-disabled: false # Allow clean in dev environment
    locations:
      - classpath:db/migration/common # Schema migrations
      - classpath:db/migration/dev # Mock data migrations

logging:
  level:
    org.sagebionetworks.bixarena: DEBUG
