# Staging profile configuration
spring:
  jpa:
    show-sql: false
  flyway:
    enabled: true
    clean-disabled: true # Never clean stage database
    locations:
      - classpath:db/migration/common # Schema migrations only

logging:
  level:
    org.sagebionetworks.bixarena: INFO
