services:
  model-ad-api:
    image: ghcr.io/sage-bionetworks/model-ad-api:${MODEL_AD_VERSION:-local}
    container_name: model-ad-api
    restart: always
    env_file:
      - ../../../apps/model-ad/api/.env
    networks:
      - model-ad
    ports:
      - '8080:8080'
    # depends_on:
    #   openchallenges-config-server:
    #     condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
