---
#
# This workflow scans the published container images
# for new vulnerabilities daily, publishing findings.
# Findings will be associated with the 'main' branch
# of the repo' in the GitHub Security tab.
#
name: Trivy Periodic Image Scan

on:
  schedule:
    # run daily
    - cron: "0 0 * * *"

jobs:
  trivy-matrix:
    name: periodic scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure image name is lower case
        id: image_name
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ghcr.io/${{ github.repository }}:main

      - name: Run Trivy
        uses: "./.github/workflows/trivy.yml"
        with:
          SOURCE_TYPE: image
          IMAGE_NAME: ${{ steps.image_name.outputs.lowercase }}
...
